#!/usr/bin/env python3
"""
Script to load secrets from a JSON file and generate a frontend config file.
This allows secrets to be stored separately and not committed to git.
"""
import json
import os
from pathlib import Path

def load_secrets():
    """Load secrets from secrets.json file"""
    # Try multiple possible locations for secrets.json
    # 1. In Docker, it might be mounted at /secrets.json
    # 2. In local dev, it's in project root
    secrets_file = None
    
    # Check if running in Docker (secrets.json mounted at /secrets.json)
    docker_secrets = Path("/secrets.json")
    if docker_secrets.exists():
        secrets_file = docker_secrets
    else:
        # Get the project root directory (parent of backend)
        project_root = Path(__file__).parent.parent
        secrets_file = project_root / "secrets.json"
    
    if not secrets_file.exists():
        print(f"Warning: {secrets_file} not found. Using empty secrets.")
        return {
            "azure": {
                "endpoint": "",
                "api_key": "",
                "api_version": "2024-12-01-preview"
            },
            "aws": {
                "region": "us-east-1",
                "access_key_id": "",
                "secret_access_key": ""
            }
        }
    
    try:
        with open(secrets_file, 'r') as f:
            secrets = json.load(f)
        print(f"Successfully loaded secrets from {secrets_file}")
        return secrets
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {secrets_file}: {e}")
        return None
    except Exception as e:
        print(f"Error reading {secrets_file}: {e}")
        return None

def generate_frontend_config(secrets):
    """Generate a JavaScript config file for the frontend"""
    # Try multiple possible locations for frontend
    # 1. In Docker, frontend is at /app
    # 2. In local dev, it's in project root/frontend
    frontend_config_dir = None
    config_file = None
    
    # Check if running in Docker (frontend at /app)
    docker_frontend = Path("/app/src/config")
    if docker_frontend.parent.exists():
        frontend_config_dir = docker_frontend
        config_file = docker_frontend / "secrets.js"
    else:
        # Get the project root directory (parent of backend)
        project_root = Path(__file__).parent.parent
        frontend_config_dir = project_root / "frontend" / "src" / "config"
        config_file = frontend_config_dir / "secrets.js"
    
    frontend_config_dir.mkdir(parents=True, exist_ok=True)
    
    # Extract secrets with defaults
    azure_endpoint = secrets.get("azure", {}).get("endpoint", "")
    azure_api_key = secrets.get("azure", {}).get("api_key", "")
    azure_api_version = secrets.get("azure", {}).get("api_version", "2024-12-01-preview")
    
    aws_region = secrets.get("aws", {}).get("region", "us-east-1")
    aws_access_key_id = secrets.get("aws", {}).get("access_key_id", "")
    aws_secret_access_key = secrets.get("aws", {}).get("secret_access_key", "")
    
    # Generate JavaScript config file
    config_content = f"""// Auto-generated file - DO NOT EDIT MANUALLY
// This file is generated by backend/load_secrets.py
// Update secrets.json and run the script to regenerate

export const SECRETS = {{
  azure: {{
    endpoint: '{azure_endpoint}',
    apiKey: '{azure_api_key}',
    apiVersion: '{azure_api_version}'
  }},
  aws: {{
    region: '{aws_region}',
    accessKeyId: '{aws_access_key_id}',
    secretAccessKey: '{aws_secret_access_key}'
  }}
}};
"""
    
    try:
        with open(config_file, 'w') as f:
            f.write(config_content)
        print(f"Successfully generated frontend config at {config_file}")
        return True
    except Exception as e:
        print(f"Error writing config file: {e}")
        return False

def main():
    """Main function"""
    print("=" * 70)
    print("  Loading Secrets and Generating Frontend Config")
    print("=" * 70)
    
    secrets = load_secrets()
    if secrets is None:
        print("Failed to load secrets. Exiting.")
        return 1
    
    if generate_frontend_config(secrets):
        print("\n" + "=" * 70)
        print("  Success! Frontend config generated.")
        print("=" * 70)
        return 0
    else:
        print("\n" + "=" * 70)
        print("  Failed to generate frontend config.")
        print("=" * 70)
        return 1

if __name__ == "__main__":
    exit(main())

