import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

/**
 * Component for displaying LLM-generated analysis in formatted markdown
 *
 * @param {string} content - Markdown content from LLM
 * @param {string} title - Optional section title
 * @param {string} icon - Optional icon/emoji to show before title
 */
export default function LLMAnalysisDisplay({ content, title, icon = '🤖' }) {
  if (!content) {
    return (
      <div className="p-6 bg-gray-50 border border-gray-200 rounded-lg">
        <p className="text-gray-500 text-sm">
          AI analysis not available. Ensure LLM is configured and tested successfully.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-6 shadow-sm">
      {title && (
        <div className="flex items-center mb-4 pb-3 border-b border-blue-300">
          <span className="text-2xl mr-2">{icon}</span>
          <h3 className="text-lg font-semibold text-gray-800">{title}</h3>
        </div>
      )}

      <div className="prose prose-sm max-w-none prose-headings:text-gray-800 prose-p:text-gray-700 prose-strong:text-gray-900 prose-ul:text-gray-700 prose-ol:text-gray-700">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {content}
        </ReactMarkdown>
      </div>

      <div className="mt-4 pt-3 border-t border-blue-200">
        <p className="text-xs text-gray-600 italic">
          ℹ️ This analysis was generated by AI and should be reviewed by domain experts.
        </p>
      </div>
    </div>
  );
}
