import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

/**
 * Component for displaying LLM-generated analysis in formatted markdown
 *
 * @param {string} content - Markdown content from LLM
 * @param {string} title - Optional section title
 * @param {string} icon - Optional icon/emoji to show before title
 */
export default function LLMAnalysisDisplay({ content, title, icon = '🤖' }) {
  if (!content) {
    return (
      <div className="p-6 bg-gray-50 border border-gray-200 rounded-lg">
        <p className="text-gray-500 text-sm">
          AI analysis not available. Ensure LLM is configured and tested successfully.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-6 shadow-sm">
      {title && (
        <div className="flex items-center mb-4 pb-3 border-b border-blue-300">
          <span className="text-2xl mr-2">{icon}</span>
          <h3 className="text-lg font-semibold text-gray-800">{title}</h3>
        </div>
      )}

      <div className="prose prose-sm max-w-none prose-headings:text-gray-800 prose-headings:mt-6 prose-headings:mb-4 prose-p:text-gray-700 prose-p:my-3 prose-p:leading-relaxed prose-strong:text-gray-900 prose-ul:text-gray-700 prose-ul:my-4 prose-ol:text-gray-700 prose-ol:my-4 prose-li:my-1.5 prose-table:border-2 prose-table:border-gray-300 prose-thead:bg-gray-100 prose-th:border prose-th:border-gray-300 prose-th:px-4 prose-th:py-2 prose-td:border prose-td:border-gray-200 prose-td:px-4 prose-td:py-2">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {content}
        </ReactMarkdown>
      </div>

      <div className="mt-4 pt-3 border-t border-blue-200">
        <p className="text-xs text-gray-600 italic">
          ℹ️ This analysis was generated by AI and should be reviewed by domain experts.
        </p>
      </div>
    </div>
  );
}
