import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

/**
 * Component for displaying LLM-generated analysis in formatted markdown
 *
 * @param {string} content - Markdown content from LLM
 * @param {string} title - Optional section title
 * @param {string} icon - Optional icon/emoji to show before title
 */
export default function LLMAnalysisDisplay({ content, title, icon = '🤖' }) {
  if (!content) {
    return (
      <div className="p-6 bg-gray-50 border border-gray-200 rounded-lg">
        <p className="text-gray-500 text-sm">
          AI analysis not available. Ensure LLM is configured and tested successfully.
        </p>
      </div>
    );
  }

  // Custom markdown components with professional styling
  const components = {
    // Headings with consistent spacing
    h1: ({ node, ...props }) => (
      <h1 className="text-2xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b-2 border-gray-200" {...props} />
    ),
    h2: ({ node, ...props }) => (
      <h2 className="text-xl font-bold text-gray-800 mt-7 mb-3.5 pb-1.5 border-b border-gray-200" {...props} />
    ),
    h3: ({ node, ...props }) => (
      <h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3" {...props} />
    ),
    h4: ({ node, ...props }) => (
      <h4 className="text-base font-semibold text-gray-700 mt-5 mb-2.5" {...props} />
    ),

    // Paragraphs with better spacing
    p: ({ node, ...props }) => (
      <p className="text-gray-700 leading-relaxed my-3" {...props} />
    ),

    // Lists with better formatting
    ul: ({ node, ...props }) => (
      <ul className="list-disc list-outside ml-6 my-4 space-y-2 text-gray-700" {...props} />
    ),
    ol: ({ node, ...props }) => (
      <ol className="list-decimal list-outside ml-6 my-4 space-y-2 text-gray-700" {...props} />
    ),
    li: ({ node, children, ...props }) => (
      <li className="pl-2" {...props}>
        <span className="font-semibold">{children}</span>
      </li>
    ),

    // Professional table styling
    table: ({ node, ...props }) => (
      <div className="overflow-x-auto my-6">
        <table className="min-w-full border-2 border-gray-400 bg-white" {...props} />
      </div>
    ),
    thead: ({ node, ...props }) => (
      <thead className="bg-gray-100" {...props} />
    ),
    tbody: ({ node, ...props }) => (
      <tbody className="divide-y divide-gray-300" {...props} />
    ),
    tr: ({ node, ...props }) => (
      <tr className="border-b border-gray-300" {...props} />
    ),
    th: ({ node, ...props }) => (
      <th className="px-4 py-3 text-left text-sm font-bold text-gray-900 border-r border-gray-400 last:border-r-0 bg-gray-100" {...props} />
    ),
    td: ({ node, ...props }) => (
      <td className="px-4 py-3 text-sm text-gray-700 border-r border-gray-300 last:border-r-0" {...props} />
    ),

    // Strong text
    strong: ({ node, ...props }) => (
      <strong className="font-bold text-gray-900" {...props} />
    ),

    // Code blocks
    code: ({ node, inline, ...props }) =>
      inline ? (
        <code className="bg-gray-100 px-1.5 py-0.5 rounded text-sm font-mono text-gray-800" {...props} />
      ) : (
        <code className="block bg-gray-100 p-4 rounded-md my-4 text-sm font-mono overflow-x-auto border border-gray-300" {...props} />
      ),

    // Blockquotes
    blockquote: ({ node, ...props }) => (
      <blockquote className="border-l-4 border-blue-500 pl-4 py-2 my-4 italic text-gray-700 bg-blue-50" {...props} />
    ),

    // Horizontal rules
    hr: ({ node, ...props }) => (
      <hr className="my-6 border-t-2 border-gray-300" {...props} />
    ),
  };

  return (
    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border-2 border-blue-300 rounded-lg p-6 shadow-sm">
      {title && (
        <div className="flex items-center mb-4 pb-3 border-b-2 border-blue-300">
          <span className="text-2xl mr-2">{icon}</span>
          <h3 className="text-lg font-semibold text-gray-800">{title}</h3>
        </div>
      )}

      <div className="prose prose-sm max-w-none">
        <ReactMarkdown remarkPlugins={[remarkGfm]} components={components}>
          {content}
        </ReactMarkdown>
      </div>

      <div className="mt-4 pt-3 border-t-2 border-blue-200">
        <p className="text-xs text-gray-600 italic">
          ℹ️ This analysis was generated by AI and should be reviewed by domain experts.
        </p>
      </div>
    </div>
  );
}
